package Modelo;
// Generated 06-jun-2020 21:33:38 by Hibernate Tools 4.3.1



/**
 * Promocion generated by hbm2java
 */
public class Promocion  implements java.io.Serializable {


     private int idPromocion;
     private String examenparcial;
     private String trentino;
     private String pandemia;

    public Promocion() {
    }

    public Promocion(int idPromocion, String examenparcial, String trentino, String pandemia) {
       this.idPromocion = idPromocion;
       this.examenparcial = examenparcial;
       this.trentino = trentino;
       this.pandemia = pandemia;
    }
   
    public int getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(int idPromocion) {
        this.idPromocion = idPromocion;
    }
    public String getExamenparcial() {
        return this.examenparcial;
    }
    
    public void setExamenparcial(String examenparcial) {
        this.examenparcial = examenparcial;
    }
    public String getTrentino() {
        return this.trentino;
    }
    
    public void setTrentino(String trentino) {
        this.trentino = trentino;
    }
    public String getPandemia() {
        return this.pandemia;
    }
    
    public void setPandemia(String pandemia) {
        this.pandemia = pandemia;
    }




}


