package Modelo;
// Generated 06-jun-2020 21:33:38 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int usuario;
     private String password;

    public Usuario() {
    }

    public Usuario(int usuario, String password) {
       this.usuario = usuario;
       this.password = password;
    }
   
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


